version: '3.8'

services:
  stbescho_apis:
    build: 
      context: /home/stbescho/text_to_gcode/api/
      dockerfile: Dockerfile
    image: stbescho_apis:0.6
    environment:
      - TRANSFORMERS_CACHE=/models
      - LOGS_DIR=/logs
      - API_PORT=5000
    volumes:
      - /home/stbescho/models:/models
      - /home/stbescho/logs:/logs
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # binds to GPU 1
            capabilities: [gpu]
